# Generated by Django 4.2.7 on 2026-01-30 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="muncipality",
            new_name="municipality",
        ),
    ]
