# Generated by Django 4.2.7 on 2026-01-30 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userprofile_date_of_birth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="seller_licience",
            new_name="seller_license",
        ),
    ]
