# Generated by Django 4.2.7 on 2026-02-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_seller_licience_userprofile_seller_license"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="receve_sms_notiifications",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="receve_sms_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
