# Generated by Django 4.2.7 on 2026-02-02 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_userprofile_receve_sms_notiifications_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="receve_sms_notifications",
            new_name="receive_sms_notifications",
        ),
    ]
